# Generated by Django 4.2.6 on 2023-10-17 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_alter_items_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='pages_item_status_205c18_idx',
            old_name='pages_items_status_238ac9_idx',
        ),
    ]
