# Generated by Django 4.2.6 on 2023-10-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_item_options_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['status']},
        ),
    ]
